# Generated by Django 3.0 on 2020-01-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20191227_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_email', models.CharField(default='', max_length=50)),
                ('contact_phonenumber', models.CharField(default='', max_length=50)),
                ('contact_description', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
