# Generated by Django 3.0 on 2020-01-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('orderupdate_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_name', models.CharField(max_length=50)),
                ('orderupdate_description', models.CharField(default='', max_length=4000)),
                ('orderupdate_timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
