# Generated by Django 3.0 on 2020-01-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_delete_orderupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('orderupdate_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default=0)),
                ('order_name', models.CharField(max_length=50)),
                ('orderupdate_description', models.CharField(default='', max_length=4000)),
                ('orderupdate_timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
