# Generated by Django 3.0 on 2020-01-13 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_orderupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderupdate',
            name='order_id',
        ),
    ]
