# Generated by Django 3.0 on 2020-02-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_orderupdate_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='orderupdate_orderid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='order_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
