# Generated by Django 3.0 on 2020-02-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200207_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='orderupdate_orderid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
