# Generated by Django 3.0 on 2020-02-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_remove_orderupdate_orderupdate_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='orderupdate_orderid',
            field=models.IntegerField(default=0),
        ),
    ]
