# Generated by Django 3.0 on 2020-02-07 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20200207_2110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
    ]
