# Generated by Django 3.0 on 2020-02-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_order_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='orderupdate_orderid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='orderupdate_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
