# Generated by Django 3.0 on 2020-02-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_auto_20200207_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='order_id_orderupdate',
            field=models.IntegerField(default=0),
        ),
    ]
