# Generated by Django 3.0 on 2020-02-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_orderupdate_order_id_orderupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='order_name',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
