# Generated by Django 3.0 on 2020-02-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_auto_20200207_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderupdate',
            name='order_id_orderupdate',
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='order_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
